### PR TITLE
update library versions

### PR DESCRIPTION
**Pull request by dazfuller**
PR to bring in the next set of changes for the excel data source.

* Update libraries to newer versions
* Bring in maxBytesForTempFiles setting to handle larger files

### CODE REVIEW

**Comment by dazfuller** [comment]
pulling in changes to address issue #18

**Comment by dazfuller** [comment]
Tested on Databricks Runtime 10.5 with 30Mb file and works fine

**Comment by pjfanning** [comment]
@dazfuller I'm not sure about the name 'maxBytesForTempFiles' -- it's more of a threshold before the byte array size is so large that we resort to using temp files.
Some alternate names:
* thresholdBytesForTempFiles
* maxBytesBeforeResortingToTempFiles

**Comment by dazfuller** [comment]
Thanks for the suggestion @pjfanning, I'll raise a separate issue to look at that now that this one has been closed and released

**Pull request merged**
